type ScheduledController = { cron: string; scheduledTime: number };
type ExecutionContext = { waitUntil(promise: Promise<unknown>): void };
interface Env {
  ADMIN_BASE_URL: string;
  CRON_PROCESS_SECRET: string;
  ASSETS: { fetch(request: Request): Promise<Response> };
}

// @ts-ignore .open-next/worker.js is generated by the Cloudflare build.
import { default as generatedWorker } from "../.open-next/worker.js";

function withSecurityHeaders(response: Response) {
  const headers = new Headers(response.headers);
  headers.set("Strict-Transport-Security", "max-age=63072000; includeSubDomains; preload");
  headers.set("X-Content-Type-Options", "nosniff");
  headers.set("X-Frame-Options", "SAMEORIGIN");
  headers.set("Referrer-Policy", "strict-origin-when-cross-origin");
  headers.set("Permissions-Policy", "camera=(), microphone=(), geolocation=(), payment=()");
  headers.set("Cross-Origin-Opener-Policy", "same-origin");
  headers.set("Content-Security-Policy-Report-Only", "default-src 'self'; script-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://challenges.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https:; connect-src 'self' https://api.resend.com https://challenges.cloudflare.com; frame-src https://challenges.cloudflare.com; frame-ancestors 'self'; form-action 'self'; base-uri 'self'; object-src 'none'");
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}

async function triggerProcessing(env: Env) {
  if (!env.CRON_PROCESS_SECRET) return;
  const url = new URL("/api/newsletters/process", env.ADMIN_BASE_URL);
  const response = await fetch(url, { method: "POST", headers: { Authorization: "Bearer " + env.CRON_PROCESS_SECRET } });
  if (!response.ok) throw new Error("Newsletter processing failed with status " + response.status);
}

const worker = {
  async fetch(request: Request, env: Env, context: ExecutionContext) {
    const url = new URL(request.url);
    let routedRequest = request;
    if (request.method === "GET" && (url.pathname === "/" || url.pathname === "/contact-us" || url.pathname === "/contact-us/")) {
      const target = new URL(request.url);
      target.pathname = url.pathname === "/" ? "/website/index.html" : "/website/contact-us.html";
      routedRequest = new Request(target.toString(), request);
      // Static site markup lives in the assets bundle, not a Next.js page.
      const assetResponse = await env.ASSETS.fetch(routedRequest);
      return withSecurityHeaders(assetResponse);
    }
    const response = await generatedWorker.fetch(routedRequest, env, context);
    return withSecurityHeaders(response);
  },
  async scheduled(_controller: ScheduledController, env: Env, context: ExecutionContext) {
    context.waitUntil(triggerProcessing(env));
  }
};

export default worker;
