type ScheduledController = {
  cron: string;
  scheduledTime: number;
};

type ExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
};

interface Env {
  ADMIN_BASE_URL: string;
  CRON_PROCESS_SECRET: string;
}

// @ts-ignore .open-next/worker.js is generated by opennextjs-cloudflare build.
import { default as generatedWorker } from "../.open-next/worker.js";

async function triggerProcessing(env: Env) {
  const url = new URL("/api/newsletters/process", env.ADMIN_BASE_URL);
  const response = await fetch(url.toString(), {
    method: "POST",
    headers: {
      Authorization: `Bearer ${env.CRON_PROCESS_SECRET}`
    }
  });

  if (!response.ok) {
    throw new Error(`Newsletter processing failed with status ${response.status}`);
  }

  return response.json();
}

const worker = {
  fetch: generatedWorker.fetch,
  async scheduled(_controller: ScheduledController, env: Env, context: ExecutionContext) {
    context.waitUntil(triggerProcessing(env));
  },
};

export default worker;